name: rse-repo-study
channels:
  - anaconda
  - defaults
dependencies:
  - pandas
  - pip
  - matplotlib
  - jupyter
  - pip:
      - beautifulsoup4
      - emoji
      - levenshtein
      - pdfminer-six
      - pydriller
      - pygithub
      - pyyaml
      - tqdm
      - unidecode