name: Build conda environment
on: [workflow_call]
jobs:
  conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info