name: test
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  github-crawl:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: ./.github/workflows/build.yml
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling script
        working-directory: ./github
        run: python3 crawl.py -f ../data/test_set.csv -n github_id -v
      - run: ls -l data/
  eprints-parse:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: ./.github/workflows/build.yml
      - name: Test parsing remote eprints
        working-directory: ./eprints
        run: python3 parse_eprints.py --repo eprints.soton.ac.uk --date 2022- --domain github.com -v
      - name: Test cleaning links
        working-directory: ./eprints
        run: python3 clean_eprints_links.py --repo eprints.soton.ac.uk --date 2022- --domain github.com -v
      - run: ls -l data/