name: test
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  github-crawl:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - run: conda list
      - run: pwd
      - run: cp config_example.cfg config.cfg
      - run: sed -i "s/<your-access-token>/${{ secrets.GITHUB_TOKEN }}/" config.cfg
      - run: cd github && python3 crawl.py -f ../data/representative_set.csv -n github_id -v
      