name: test
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  github-crawl-contents:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling contents script
        working-directory: ./src/github
        run: python3 crawl_contents.py -f ../../data/debug/test_set.csv -n github_id -v
      - run: ls -l data/
  github-crawl-contributions:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling contributions script
        working-directory: ./src/github
        run: python3 crawl_contributions.py -f ../../data/debug/test_set.csv -n github_id -v
      - run: ls -l data/raw/github
  github-crawl-engagement:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling engagement script
        working-directory: ./src/github
        run: python3 crawl_engagement.py -f ../../data/debug/test_set.csv -n github_id -v
      - run: ls -l data/raw/github       
  github-crawl-issues:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling issues script
        working-directory: ./src/github
        run: python3 crawl_issues.py -f ../../data/debug/test_set.csv -n github_id -v
      - run: ls -l data/raw/github    
  github-crawl-metadata:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test crawling issues script
        working-directory: ./src/github
        run: python3 crawl_metadata.py -f ../../data/debug/test_set.csv -n github_id -v
      - run: ls -l data/raw/github         
  eprints-parse:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - run: conda info
      - name: Setup personal access token
        run: |
          cp config_example.cfg config.cfg
          sed -i "s/<your-access-token>/${{ secrets.TOKEN_TEST }}/" config.cfg
      - name: Test parsing remote eprints
        working-directory: ./src/eprints
        run: python3 parse_eprints.py --repo eprints.soton.ac.uk --date 2022-2023 -v
      - name: Test parsing PDFs
        working-directory: ./src/eprints
        run: python3 parse_pdfs.py --repo eprints.soton.ac.uk --date 2022-2023 --domain github.com -v
      - name: Test cleaning links
        working-directory: ./src/eprints
        run: python3 clean_eprints_links.py --repo eprints.soton.ac.uk --date 2022-2023 --domain github.com -v
      - run: ls -l data/raw/eprints
  aggregate_data:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: rse-repo-study
          environment-file: environment.yml
          auto-activate-base: false
      - name: Aggregate
        working-directory: ./src/analysis
        run: python3 aggregate_datasets.py -v
      - run: ls -l data/derived