name: test
run-name: ${{ github.actor }} is running tests
on: [push]
jobs:
  github-crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
      - run: conda info
      - run: conda list
      - run: pwd
      - run: python3 github/crawl.py -f data/representative_set.csv -n github_id -v
      